config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :registrations => "registrations",
                                        omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'
  resources :user do
    collection do
      get "landing"
      get "dashboard"
      get "keywords"
      get "reports"
      get "setting"
      get "ads_manager"

      get "get_data"
      get "login"
      post "verify_payment"
      get "verify_username"
      post "connect_facebook"
      get "get_fb_token"
      post "disconnect_facebook"
      get "profile"
    end  
  end 

  resources :home do
    collection do
      get "get_viralstyle"
      get "get_teechip"
      get "get_represent"

      get "get_top_campaigns"
      get "get_top_graph"
      get "get_top_summary"
      get "get_campaign_details"
    end  
  end  

  resources :payment

end

app/views/shared/_footer.html.erb
<div class="footer">  
    <div>
        Copyright © 2014-2015 StealthROI. All rights reserved.
    </div>
</div>

app/views/shared/_header.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2  " href="#"><img src="/assets/toggle.png" alt="pic"/> </a> 
        </div>
        <%= render :partial => "/shared/top_right_navbar" %>
    </nav>
</div>

app/views/shared/_left_side_menu.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header text-center">
                <div class="dropdown profile-element"> <span>
                <div class="logo-main"><img src="/assets/logo_white.png" alt="pic"/></div>
                        <img alt="image" class="img-circle" src="<%=current_user.remote_avatar_url.nil? ? (current_user.avatar_url.nil? ? "/assets/default.jpg" : current_user.avatar_url) : current_user.remote_avatar_url %>" style="width:108px;height:108px" />
                         </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear"> <span class="block m-t-xs"> <%= (current_user.first_name.nil? || current_user.first_name.empty? ? current_user.fname : "#{current_user.first_name} #{current_user.last_name}" )%>
                         </span> <span class="text-muted text-xs block">Administrator </span> </span> </a>
                    
                </div>
                <div class="logo-element">
                    <img src="/assets/logo_icon.png" alt="pic"/>
                </div>
            </li>
            <li class="<%= 'active' if params[:action] == 'dashboard' %>">
                <!-- <a href="/user/dashboard"><i class="fa fa-tachometer"></i> <span class="nav-label">Dashboards</span> <span class="fa arrow"></span></a> -->
                <%= link_to '<i class="fa fa-tachometer"></i> <span class="nav-label">Dashboards</span> <span class="fa arrow"></span></a>'.html_safe, "/user/dashboard", method: :get %>
                
            </li>
            <li class="<%= 'active' if params[:action] == 'reports' %>">
                <!-- <a href="/user/reports"><i class="fa fa-file-text-o"></i> <span class="nav-label">Reports</span><span class="fa arrow"></span></a> -->
                 <%= link_to '<i class="fa fa-file-text-o"></i> <span class="nav-label">Reports</span> <span class="fa arrow"></span></a>'.html_safe, "/user/reports", method: :get %>
            </li>
            <li class="<%= 'active' if params[:action] == 'ads_manager' %>">
                <!-- <a href="/user/ads_manager"><i class="fa fa-bullhorn"></i> <span class="nav-label">Ads Manager</span><span class="fa arrow"></span></a> -->
                 <%= link_to '<i class="fa fa-bullhorn"></i> <span class="nav-label">Ads Manager</span> <span class="fa arrow"></span></a>'.html_safe, "/user/ads_manager", method: :get %>
                
            </li>
            <li class="<%= 'active' if params[:action] == 'keywords' %>">
                <!-- <a href="/user/keywords"><i class="fa fa-key"></i> <span class="nav-label">Keywords</span><span class="fa arrow"></span></a> -->
                 <%= link_to '<i class="fa fa-key"></i> <span class="nav-label">Keywords</span> <span class="fa arrow"></span></a>'.html_safe, "/user/keywords", method: :get %>
                
            </li>
            <li class="<%= 'active' if params[:action] == 'setting' %>">
                <!-- <a href="/user/setting"><i class="fa fa-cog"></i> <span class="nav-label">Settings</span><span class="fa arrow"></span></a> -->
                 <%= link_to '<i class="fa fa-cog"></i> <span class="nav-label">Settings</span> <span class="fa arrow"></span></a>'.html_safe, "/user/setting", method: :get %>
                
            </li>
        </ul>

    </div>
</nav>

app/views/shared/_signin.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <%if params[:controller] == "home"%>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><img src="/assets/close.png" alt=""/></span></button>
      <%end%>
      <h4 class="modal-title" id="myModalLabel">LOGIN</h4>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-12">
          <h3>Login With:</h3>
          <p class="social-login">
            <a href="<%= user_omniauth_authorize_path(:facebook) %>" class="popup" id="facebook"><img src="/assets/fb-login.png" alt=""/></a>
              <a href="<%= user_omniauth_authorize_path(:google_oauth2) %>" class="popup" id="google_oauth2"><img src="/assets/google-login.png" alt=""/></a>
              <a href="<%= user_omniauth_authorize_path(:twitter) %>" class="popup" id="twitter"><img src="/assets/twitter-login.png" alt=""/></a>
          </p>  
        </div>
        <div class="col-md-7 col-sm-7 col-xs-12">
          <h3>Sign In With:</h3>
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class=" form-group input-group input-group-lg">
              <span class="input-group-addon" id="sizing-addon1"><img src="/assets/email.png" alt="" width="26" height="19"/></span>
              <%= f.text_field :login,:class=>"form-control",placeholder:"Username or Email", "aria-describedby"=>"sizing-addon1",:required=>"required" %>
              <!-- <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1" required> -->
            </div>
            <div class="form-group input-group input-group-lg">
              <span class="input-group-addon" id="sizing-addon1"><img src="/assets/lock.png" alt="" width="26" height="19"/></span>
              <%= f.password_field :password,:class=>"form-control",placeholder:"Password", "aria-describedby"=>"sizing-addon1",:required=>"required" %>
              <!-- <input type="password" class="form-control" placeholder="Password" aria-describedby="sizing-addon1" required> -->
            </div>
            
            <div class=" form-group">
              <div class="checkbox">
                <%= f.check_box :remember_me,id: "check2",value: "check1" %>
                <!-- <input id="check2" type="checkbox" name="user[remember_me]" value="check1"> -->
                <label for="check2">Remember Me</label>
              </div>
            </div>
            <%= f.submit 'Sign In', class: 'btn-default-theme' %>
          <%end%>
          <% if params[:controller] == "home"%>
            <p class="links-popup">
              <a href="javascript:void(0);" data-toggle="modal" data-target="#resetModal" data-dismiss="modal" arial-label="Close">I forget my password </a>
              <a href="javascript:void(0);" data-toggle="modal" data-target="#signupModal"  data-dismiss="modal" aria-label="Close">Register a new membership</a>
            </p>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_signup.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <%if params[:controller] == "home"%>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><img src="/assets/close.png" alt=""/></span></button>
      <%end%>
      <h4 class="modal-title" id="myModalLabel">SIGNUP</h4>
      <h5 class="error_msg" style="color:red;display:none"></h5>
      <!-- <h5 class="success_msg" style="color:green;display:none">Successful Payment.</h5> -->
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-5">
        	<h3>SignUp With :</h3>
          <p class="social-login">
          	<a href="<%= user_omniauth_authorize_path(:facebook) %>" class="popup" id="facebook"><img src="/assets/fb-signup.png" alt=""/></a>
            <a href="<%= user_omniauth_authorize_path(:google_oauth2) %>" class="popup" id="google_oauth2" ><img src="/assets/google-signup.png" alt=""/></a>
            <a href="<%= user_omniauth_authorize_path(:twitter) %>" class="popup" id="twitter"><img src="/assets/twitter-signup.png" alt=""/></a>
          </p>	
        </div>
        <div class="col-md-7">
        	<h3>Register a new Account:</h3>
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: "sign_up_form"} ) do |f| %>
            <%= devise_error_messages! %>
            <div class="signup_box">
              <div class=" form-group input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1"><img src="/assets/user.png" alt="" width="26" height="19"/></span>
                <%= f.text_field :fname,:class=>"form-control",placeholder:"Username", "aria-describedby"=>"sizing-addon1",:required=>"required" %>
                <!-- <input type="text" class="form-control" placeholder="Full Name" aria-describedby="sizing-addon1"> -->
	            </div>
              <div class="form-group input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1"><img src="/assets/email.png" alt="" width="26" height="19"/></span>
                <%= f.email_field :email,:class=>"form-control",placeholder:"Email", "aria-describedby"=>"sizing-addon1",:required=>"required" %>
                <!-- <input type="text" class="form-control" placeholder="Email" aria-describedby="sizing-addon1"> -->
	            </div>
              <div class=" form-group input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1"><img src="/assets/lock.png" alt="" width="26" height="19"/></span>
                <%= f.password_field :password,:class=>"form-control",placeholder:"Enter Password", "aria-describedby"=>"sizing-addon1",:required=>"required" %>
                <!-- <input type="text" class="form-control" placeholder="Enter Password" aria-describedby="sizing-addon1"> -->
	            </div>
              <div class=" form-group input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1"><img src="/assets/retyp.png" alt="" width="26" height="19"/></span>
                <%= f.password_field :password_confirmation,:class=>"form-control",placeholder:"Retype Password", "aria-describedby"=>"sizing-addon1",:required=>"required" %>
                <!-- <input type="text" class="form-control" placeholder="Retype Password" aria-describedby="sizing-addon1"> -->
	            </div>
              
              <div class=" form-group">
                <div class="checkbox">
                  <input id="check1" type="checkbox" name="check" value="check1" required>
                  <label for="check1">I agree to <a href="#">terms</a></label>
                </div>
              </div>
              <!-- <button class="btn-default-theme" id="next_btn" type="submit">Next</button> -->
              <%= f.submit 'Sign Up', class: 'btn-default-theme', id: "signup_btn" %>
            </div>
<%
=begin%>
            <div class="payment_box" style="display:none">
              <div class=" form-group input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1"><img src="/assets/retyp.png" alt="" width="26" height="19"/></span>
                <%= f.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]], :class=> "form-control" %>
                <!-- <input type="text" class="form-control" placeholder="Retype Password" aria-describedby="sizing-addon1"> -->
              </div>
              <div class=" form-group input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1"><img src="/assets/user.png" alt="" width="26" height="19"/></span>
                <%= f.text_field :card_name,:class=>"form-control",placeholder:"Card Name", "aria-describedby"=>"sizing-addon1" %>
                <!-- <input type="text" class="form-control" placeholder="Full Name" aria-describedby="sizing-addon1"> -->
              </div>
              <div class="form-group input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1"><img src="/assets/card_number.png" alt="" width="26" height="19" style="width:30px;height:30px" /></span>
                <%= f.text_field :card_number,:class=>"form-control",placeholder:"Card Number", "aria-describedby"=>"sizing-addon1" %>
                <!-- <input type="text" class="form-control" placeholder="Email" aria-describedby="sizing-addon1"> -->
              </div>
              <div class=" form-group input-group input-group-lg" style="float:right;width: <%= params[:controller] == 'home' ? '200px' : '100%' %>">
                <span class="input-group-addon" id="sizing-addon1"><img src="/assets/lock.png" alt="" width="26" height="19"/></span>
                <%= f.text_field :cvv,:class=>"form-control",placeholder:"CVV", "aria-describedby"=>"sizing-addon1" %>
                <!-- <input type="text" class="form-control" placeholder="Enter Password" aria-describedby="sizing-addon1"> -->
              </div>
              <div class=" form-group input-group input-group-lg" style="width: <%= params[:controller] == 'home' ? '300px' : '100%' %>">
                <span class="input-group-addon" id="sizing-addon1"><img src="/assets/calender.png" alt="" width="26" height="19" style="width:30px;height:30px" /></span>
                <%= f.date_select :card_expires_on, discard_day: true, start_year: Date.today.year, end_year: (Date.today.year+10), class: "form-control", required: true %>
                <!-- <input type="text" class="form-control" placeholder="Enter Password" aria-describedby="sizing-addon1"> -->
              </div>
              <%= f.hidden_field :payment_status,value: "false", class: "payment_status" %>

              <%= f.submit 'Sign Up', class: 'btn-default-theme', id: "signup_btn" %>
              <a href="#" id="back_btn">Back</a>
            </div>
<%
=end%>
          <%end%>
          <% if params[:controller] == "home"%>
            <p class="links-popup">
              <a href="javascript:void(0);" data-toggle="modal" data-target="#loginModal"  data-dismiss="modal" aria-label="Close">I already have an account.</a>
            </p>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#next_btn").click(function(e){
    e.preventDefault();
    e.stopPropagation();

    // if ($($('form')[1]).valid()){
    //   $(".signup_box").hide()
    //   $(".payment_box").show()
    // }
    $.ajax({
      type: 'get',
      url: '/user/verify_username',
      data: "username="+$("#user_fname").val(),
      success: function(res){
          if(res.status == false){
              // var status = "false";
          }else{
              // var status = "true";
              if ($($('form.sign_up_form')[0]).valid()){
              $(".signup_box").hide()
              $(".payment_box").show()
            }
          }
      }
    })
  })

  //  $("#back_btn").click(function(e){
  //   e.preventDefault();
  //   $(".signup_box").show()
  //   $(".payment_box").hide()
  // })

  //  $("#signup_btn, #payment_btn").click(function(e){
  //   e.preventDefault();
  //   if ($('#preview1').html() == ""){
  //     var opts = {
  //             lines: 17,
  //             length: 40,
  //             width: 22,
  //             radius: 60,
  //             corners: 1,
  //             rotate: 90,
  //             direction: 1,
  //             color: '#000',
  //             speed: 1.3,
  //             trail: 96,
  //             shadow: false,
  //             hwaccel: false,
  //             className: 'spinner',
  //             zIndex: 2e9,
  //             top: '50%',
  //             left: '50%'
  //     };
  //     var target = document.getElementById('preview1');
  //     var spinner = new Spinner(opts).spin(target);
  //     target.appendChild(spinner.el);

  //     var card_name = $(this).parent().find("#user_card_name").val();
  //     var card_number = $(this).parent().find("#user_card_number").val();
  //     var cvv = $(this).parent().find("#user_cvv").val();
  //     var card_type = $(this).parent().find("#user_card_type").val();
  //     var card_year = $(this).parent().find("#user_card_expires_on_1i").val();
  //     var card_month = $(this).parent().find("#user_card_expires_on_2i").val();
  //     var src = $(this)

  //     $.ajax({
  //       type: 'post',
  //       url: '/user/verify_payment',
  //       // async: false,
  //       data: 'card_name='+card_name+'&card_number='+card_number+'&cvv='+cvv+'&card_type='+card_type+'&card_year='+card_year+'&card_month='+card_month,
  //       success: function(e){
  //         if (e.status == true){
  //           $(".payment_status").val("true")
  //           target.removeChild(spinner.el);
  //           // $(".success_msg").css("display","block")
  //           // notice_box("Successful Payment.")
  //           $(src.parent().parent()[0]).submit()
  //         }else{
  //           var msg = JSON.stringify(e.message) 
  //           // $(".error_msg").html(msg).css("display","block")
  //           $('#signupModal').animate({scrollTop: '100px'}, 300);
  //           console.log(e.message)
  //           alert_box(msg)
  //           target.removeChild(spinner.el);
  //           // setTimeout(function(){
  //           //   $('.error_msg').slideUp();
  //           // }, 10000);
  //         }
          
  //       },
  //       error: function(){
  //         target.removeChild(spinner.el);
  //         alert('Something went wrong.')
  //       }
  //     })
  //   }  
  // })
</script>

<style type="text/css">
  select {
    background-color: #fff;
    border: 1px solid #454545;
    border-left: 0px;
    border-radius: 0px;
    height: 80px;
    width: 100%
    }
    #user_card_expires_on_1i{
      float: right;
    }
    #user_card_expires_on_1i,#user_card_expires_on_2i{
      width: 50%;
      padding: 10px;
    }
    label.error{
      font-weight: 0;
      display: table-caption;
      width: 100%;
      padding: 0;
      margin: 0;
      font-size: 12px;
    }
    .input-group-lg label:before{
      border:none !important;
      width: 0 !important;
      height: 0 !important;
    }
</style>

app/views/shared/_top_right_navbar.html.erb
<%@notifications = current_user.notifications.all%>
<ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
            <img src="/assets/bell.png"/>  <!-- <span class="label label-primary">8</span> -->
        </a>
        <div class="dropdown-menu dropdown-alerts c1">
        	<h3>You have <%=@notifications.count%> notifications</h3>
            <ul class="slim-scroll-notification">
                <% @notifications.each do |obj| %>            
                    <li>
                        <div class="notification_buzz">
                        	<div class="notify pull-left">
                            	<%= obj.notification_text %>
                                <!-- Total ad-spent for Teechip <br/>yesterday was $759.77 -->
                            </div>
                            <div class="time_image pull-right">
                            	<span class="time_exist">
                                    <span data-livestamp=<%="#{obj.created_at.to_i}"%> ></span>
                                	<%#= (Time.zone.now - obj.created_at)/1.hour < 1 ? ((Time.zone.now - obj.created_at)/1.minutes).to_i.to_s+" minutes ago" : ((Time.zone.now - obj.created_at)/1.hour > 24 ? ((Time.zone.now - obj.created_at)/1.days).to_i.to_s+" days ago" : ((Time.zone.now - obj.created_at)/1.hour).to_i.to_s+" hours ago" )%>
                                </span>
                                <span class="dollar_sign">
                                	<img src="/assets/dollar_notify.png" alt=""/>
                                </span>
                            </div>
                        </div>
                    </li>
                <% end %>
            <!-- <li>
                <div class="notification_buzz">
                	<div class="notify pull-left">
                    	Total ad-spent for Teechip <br/>yesterday was $759.77
                    </div>
                    <div class="time_image pull-right">
                    	<span class="time_exist">
                        	2 hours
                        </span>
                        <span class="dollar_sign">
                        	<img src="/assets/dollar_notify.png" alt=""/>
                        </span>
                    </div>
                </div>
            </li>
            <li>
                <div class="notification_buzz">
                	<div class="notify pull-left">
                    	Total ad-spent for Teechip <br/>yesterday was $759.77
                    </div>
                    <div class="time_image pull-right">
                    	<span class="time_exist">
                        	2 hours
                        </span>
                        <span class="dollar_sign">
                        	<img src="/assets/dollar_notify.png" alt=""/>
                        </span>
                    </div>
                </div>
            </li>
            <li>
                <div class="notification_buzz">
                	<div class="notify pull-left">
                    	Total ad-spent for Teechip <br/>yesterday was $759.77
                    </div>
                    <div class="time_image pull-right">
                    	<span class="time_exist">
                        	2 hours
                        </span>
                        <span class="dollar_sign">
                        	<img src="/assets/dollar_notify.png" alt=""/>
                        </span>
                    </div>
                </div>
            </li>
            <li>
                <div class="notification_buzz">
                	<div class="notify pull-left">
                    	Total ad-spent for Teechip <br/>yesterday was $759.77
                    </div>
                    <div class="time_image pull-right">
                    	<span class="time_exist">
                        	2 hours
                        </span>
                        <span class="dollar_sign">
                        	<img src="/assets/dollar_notify.png" alt=""/>
                        </span>
                    </div>
                </div>
            </li> -->
            </ul>
           
            <div class="text-center link-block last-child-div">
                <a href="#">
                    View All
                </a>
            </div>
        </div>
    </li>
    <!-- <li class="dropdown">
        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
            <img src="/assets/message.png"/>  <span class="label label-primary">16</span>
        </a>
        <div class="dropdown-menu dropdown-alerts c1">
        	<h3>You have 2 Messages</h3>
            <ul class="slim-scroll-notification">
            <li>
                <div class="notification_buzz">
                	<div class="message_left pull-left">
                    	<img src="/assets/user_message.png" alt="pic"/>
                    </div>
                    <div class="message_right pull-right">
                    	<div class="message_top">
                        	<div class="user_name">John Oate</div>
                            <div class="time_ago">2 hours ago</div>
                        </div>
                        <div class="message_botttom">
                        	Lorem ipsum dolor sit amet.
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="notification_buzz">
                	<div class="message_left pull-left">
                    	<img src="/assets/user_message.png" alt="pic"/>
                    </div>
                    <div class="message_right pull-right">
                    	<div class="message_top">
                        	<div class="user_name">John Oate</div>
                            <div class="time_ago">2 hours ago</div>
                        </div>
                        <div class="message_botttom">
                        	Lorem ipsum dolor sit amet.
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="notification_buzz">
                	<div class="message_left pull-left">
                    	<img src="/assets/user_message.png" alt="pic"/>
                    </div>
                    <div class="message_right pull-right">
                    	<div class="message_top">
                        	<div class="user_name">John Oate</div>
                            <div class="time_ago">2 hours ago</div>
                        </div>
                        <div class="message_botttom">
                        	Lorem ipsum dolor sit amet.
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="notification_buzz">
                	<div class="message_left pull-left">
                    	<img src="/assets/user_message.png" alt="pic"/>
                    </div>
                    <div class="message_right pull-right">
                    	<div class="message_top">
                        	<div class="user_name">John Oate</div>
                            <div class="time_ago">2 hours ago</div>
                        </div>
                        <div class="message_botttom">
                        	Lorem ipsum dolor sit amet.
                        </div>
                    
                    </div>
                </div>
            </li>
            <li>
                <div class="notification_buzz">
                	<div class="message_left pull-left">
                    	<img src="/assets/user_message.png" alt="pic"/>
                    </div>
                    <div class="message_right pull-right">
                    	<div class="message_top">
                        	<div class="user_name">John Oate</div>
                            <div class="time_ago">2 hours ago</div>
                        </div>
                        <div class="message_botttom">
                        	Lorem ipsum dolor sit amet.
                        </div>
                    </div>
                </div>
            </li>
            </ul>
           
            <div class="text-center link-block last-child-div">
                <a href="#">
                    View All Messages
                </a>
            </div>
        </div>
    </li>
    <li class="dropdown">
        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
            <img src="/assets/status.png"/>  <span class="label label-primary">16</span>
        </a>
    </li> -->
    <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <span class="clear">  <span class="text-muted text-xs block"><img src="<%=current_user.remote_avatar_url.nil? ? (current_user.avatar_url.nil? ? "/assets/default.jpg" : current_user.avatar_url) : current_user.remote_avatar_url %>" style="width:40px;height:40px;border-radius:20px"/><%= (current_user.first_name.nil? || current_user.first_name.empty? ? current_user.fname : "#{current_user.first_name} #{current_user.last_name}" )%> <b class="caret"></b></span> </span> </a>
            <div class="dropdown-menu dropdown-alerts c2">
        	
            <ul class="user-dropdown">
            <li class="active">
                <a href="#">
                	<i class="fa fa-user"></i> My Profile
                </a>
            </li>
            <li>
                <a href="/user/setting">
                	<i class="fa fa-cog"></i> Setting
                </a>
            </li>
            <li>
                <a href="#">
                	<i class="fa fa-question-circle"></i> Help
                </a>
            </li>
            <li>
                <!-- <a href="/">
                	<i class="fa fa-sign-out"></i> Logout
                </a> -->
                <%= link_to '<i class="fa fa-sign-out"></i> Logout'.html_safe, destroy_user_session_path, method: :delete %>
            </li>
            </ul>
        </div>
    </li>
</ul>