config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :registrations => "registrations",
                                        omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'
  resources :user do
    collection do
      get "landing"
      get "dashboard"
      get "keywords"
      get "reports"
      get "setting"
      get "ads_manager"

      get "get_data"
      get "login"
      post "verify_payment"
      get "verify_username"
      post "connect_facebook"
      get "get_fb_token"
      post "disconnect_facebook"
      get "profile"
    end  
  end 

  resources :home do
    collection do
      get "get_viralstyle"
      get "get_teechip"
      get "get_represent"

      get "get_top_campaigns"
      get "get_top_graph"
      get "get_top_summary"
      get "get_campaign_details"
    end  
  end  

  resources :payment

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user

  attr_accessor :card_type, :card_number,:address,:city,:state,:postal_code,:country_code,:cvv2,:card_expires_on
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
	before_action :authenticate_user!
	# include PayPal::SDK::REST

	def index
		@payment = current_user.build_payment if current_user.payment.nil?
	end

	# def new
	# 	#if current_user.payment.nil?
	# 		@payment = current_user.build_payment
	# 	# else
	# 	# 	redirect_to root_url, alert: "Payment is already done"
	# 	# end
	# end

	def create
		# @payment = Payment.new({
		#   :intent => "sale",
		#   :payer => {
		#     :payment_method => "credit_card",
		#     :funding_instruments => [{
		#       :credit_card => {
		#       	:type => params[:payment][:card_type], #"visa",
		#         :number => params[:payment][:card_number], #"4242424242424242",
		#         :expire_month => params[:payment]["card_expires_on(2i)"], #"1",
		#         :expire_year => params[:payment]["card_expires_on(1i)"], #"2018",
		#         :cvv2 => params[:payment][:cvv2], #"874",
		#         :first_name => params[:payment][:first_name], #"Joe",
		#         :last_name => params[:payment][:last_name], #"Shopper",
		#         :billing_address => {
		#           :line1 => params[:payment][:address], #"52 N Main ST",
		#           :city => params[:payment][:city], #"Johnstown",
		#           :state => params[:payment][:state], #"OH",
		#           :postal_code => params[:payment][:postal_code], #"43210",
		#           :country_code => params[:payment][:country_code] #"US" 
		#           }}}]},
		#   :transactions => [{
		#     :amount => {
		#       :total => "10.00",
		#       :currency => "USD" },
		#     :description => "This is the payment transaction description." }]})

		# @payment.create
		# if @payment.id.nil?
		# 	error = @payment.error
		# 	redirect_to payment_index_url, :alert => error.name+"\n"+error.details.to_s
		# else
		# 	params[:payment][:transaction_id] = @payment.id
		# 	params[:payment][:amount] = 10
		# 	@data = current_user.build_payment(payment_params)
		# 	if @data.save
		# 		redirect_to payment_index_url, :notice => "Payment Done with payment id #{@payment.id}"
		# 	else
		# 		redirect_to payment_index_url, :alert => "Something went wrong."
		# 	end
		# end
	end

	def destroy
		if current_user.payment.id == params[:id].to_i
			current_user.payment.delete
			redirect_to root_url
		else
			redirect_to root_url, alert: "Something went wrong."
		end
	end

	private

    def payment_params
      params.require(:payment).permit(:first_name, :last_name,:amount,:transaction_id,:user_id)
    end
	
end

app/views/payment/new.html.erb
<div class="field payment_method">
  <fieldset class="card_info">
    <legend>Card info</legend>
    <%= form_for @payment, url: payment_index_path do |c| %>
      <div class="field">
        <%= c.label :first_name %>
        <%= c.text_field :first_name %>
      </div>
      <div class="field">
        <%= c.label :last_name %>
        <%= c.text_field :last_name %>
      </div>
      <div class="field">
        <%= c.label :card_type %>
        <%= c.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]] %>
      </div>
      <div class="field">
        <%= c.label :card_number %>
        <%= c.text_field :card_number %>
      </div>

      <div class="field">
        <%= c.label :address %>
        <%= c.text_field :address %>
      </div>
      <div class="field">
        <%= c.label :city %>
        <%= c.text_field :city %>
      </div>
      <div class="field">
        <%= c.label :state %>
        <%= c.text_field :state %>
      </div>
      <div class="field">
        <%= c.label :postal_code %>
        <%= c.text_field :postal_code %>
      </div>
      <div class="field">
        <%= c.label :country_code %>
        <%= c.text_field :country_code %>
      </div>

      <div class="field">
        <%= c.label :card_verification, "Card Verification Value (CVV)" %>
        <%= c.text_field :cvv2 %>
      </div>
      <div class="field">
        <%= c.label :card_expires_on %>
        <%= c.date_select :card_expires_on, start_year: Date.today.year, end_year: (Date.today.year+10) %>
      </div>

      <div class="actions">
        <%= c.submit "Registration Payment", class: "btn", style: "color: white;background: rgb(242, 118, 73);" %>
      </div>

    <% end %>
  </fieldset>
</div>